## Read CSV File

- A simple way to store big data set is to use csv file (comma seprated file).

- CSV file contain plain text and well know format that can be read by everone including Pandas

In [10]:
import pandas as pd
csv = pd.read_csv(r"C:\Users\ankul\Downloads\ank.csv")

In [11]:
csv

,SYMBOL,SECURITY,TODAY - VILUME,AVG - VOLUME,CHANGE,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11
0,ELECTHERM,Electrotherm,473907,9457,50.110003,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NBIFIN,N. B. I. Industrial Finance Company,5754,154,37.202586,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,HINDCON,Hindcon Private Limited,304759,9248,32.953450,NaN,NaN,NaN,NaN,NaN,NaN,
3,GKWLIMITED,GKW Limited,21375,711,30.049203,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,21STCENMGM,21st Century Management Service,110375,3879,28.450831,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,ALPHAGEO,Alphageo (India) Limited,232755,8356,27.852613,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,UNIENTER,Uniphos Enterprised Limited,162601,7553,21.528002,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,JAGSNPHARM,Jagsonpal Pharmaceutical Limited,1301892,73134,17.801420,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,SKMEGGPROD,SKM Egg Products Exportsn(India) Limited,1541130,87775,17.557733,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,SWELELCTES,Swelect Energy System Limited,207954,12276,16.938733,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,NAHARPOLY,Nahar Poly Film Limited,600043,38574,15.555297,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,PODDARHOUS,Poddar Housing and Development,46040,3012,15.283833,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,LINC,Linc Limited,60551,4076,14.853673,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,SHIVAMILLS,Shiva Mills Limited,142943,10391,13.755541,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,PDMJEPAPER,Pudumjee Paper Products Limited,1316284,102646,12.892143,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,DSSL,Dynacons System & Solution,263641,23439,11.247963,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,ANDREWYU,Andrew Yule & Company & Limited,2408026,230048,10.641332,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,LAXMICOT,Laxmi Costpin Limited,198503,19007,10.443312,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,REPL,Rudrabhishek Enterprises Limited,660281,65700,10.049911,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,PILITA,PIL ITALICA LIFESTYLE LIMITED,6864080,685602,10.017751,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,BHAGYAPROP,Bhagyanagar Properties Limited,305594,30596,9.987766,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,MUNJALAU,Munjal Auto Industries Limited,705322,82307,8.569312,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,ALKALI,Alkalis Metals Limited,157496,19069,8.563313,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,INTENTECH,Intense Technologies Limited,1252606,164644,7.607959,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,INDORAMA,Indo Rama Synthetic (India) Limited,679204,89288,7.606862,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [12]:
csv.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25 entries, 0 to 24
Data columns (total 12 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   SYMBOL          25 non-null     object
 1   SECURITY        25 non-null     object
 2   TODAY - VILUME  25 non-null     int64
 3   AVG - VOLUME    25 non-null     int64
 4   CHANGE          25 non-null     float64
 5   Unnamed: 5      0 non-null      float64
 6   Unnamed: 6      0 non-null      float64
 7   Unnamed: 7      0 non-null      float64
 8   Unnamed: 8      0 non-null      float64
 9   Unnamed: 9      0 non-null      float64
 10  Unnamed: 10     0 non-null      float64
 11  Unnamed: 11     1 non-null      object
dtypes: float64(7), int64(2), object(3)
memory usage: 2.5+ KB

In [18]:
csv.head()

,SYMBOL,SECURITY,TODAY - VILUME,AVG - VOLUME,CHANGE,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11
0,ELECTHERM,Electrotherm,473907,9457,50.110003,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NBIFIN,N. B. I. Industrial Finance Company,5754,154,37.202586,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,HINDCON,Hindcon Private Limited,304759,9248,32.953450,NaN,NaN,NaN,NaN,NaN,NaN,
3,GKWLIMITED,GKW Limited,21375,711,30.049203,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,21STCENMGM,21st Century Management Service,110375,3879,28.450831,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [19]:
csv.describe()

,TODAY - VILUME,AVG - VOLUME,CHANGE,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10
count,2.500000e+01,25.000000,25.000000,0.0,0.0,0.0,0.0,0.0,0.0
mean,8.009246e+05,71237.680000,17.900822,NaN,NaN,NaN,NaN,NaN,NaN
std,1.395095e+06,139964.620859,10.796906,NaN,NaN,NaN,NaN,NaN,NaN
min,5.754000e+03,154.000000,7.606862,NaN,NaN,NaN,NaN,NaN,NaN
25%,1.574960e+05,8356.000000,10.049911,NaN,NaN,NaN,NaN,NaN,NaN
50%,3.047590e+05,19069.000000,14.853673,NaN,NaN,NaN,NaN,NaN,NaN
75%,7.053220e+05,82307.000000,21.528002,NaN,NaN,NaN,NaN,NaN,NaN
max,6.864080e+06,685602.000000,50.110003,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
## method to find the first row using iloc method
print(csv.iloc[0])

SYMBOL               ELECTHERM
SECURITY          Electrotherm
TODAY - VILUME          473907
AVG - VOLUME              9457
CHANGE               50.110003
Unnamed: 5                 NaN
Unnamed: 6                 NaN
Unnamed: 7                 NaN
Unnamed: 8                 NaN
Unnamed: 9                 NaN
Unnamed: 10                NaN
Unnamed: 11                NaN
Name: 0, dtype: object

In [ ]:
## nrow useful for getting any particulat row.
import pandas as pd
csv = pd.read_csv(r"C:\Users\ankul\Downloads\ank.csv", nrows=3)

In [23]:
csv

,SYMBOL,SECURITY,TODAY - VILUME,AVG - VOLUME,CHANGE,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11
0,ELECTHERM,Electrotherm,473907,9457,50.110003,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NBIFIN,N. B. I. Industrial Finance Company,5754,154,37.202586,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,HINDCON,Hindcon Private Limited,304759,9248,32.953450,NaN,NaN,NaN,NaN,NaN,NaN,

In [25]:
## nrow useful for getting any particulat column.
csv = pd.read_csv(r"C:\Users\ankul\Downloads\ank.csv", usecols=["SYMBOL"])

In [27]:
csv

        SYMBOL
0    ELECTHERM
1       NBIFIN
2      HINDCON
3   GKWLIMITED
4   21STCENMGM
5     ALPHAGEO
6     UNIENTER
7   JAGSNPHARM
8   SKMEGGPROD
9   SWELELCTES
10   NAHARPOLY
11  PODDARHOUS
12        LINC
13  SHIVAMILLS
14  PDMJEPAPER
15        DSSL
16    ANDREWYU
17    LAXMICOT
18        REPL
19      PILITA
20  BHAGYAPROP
21    MUNJALAU
22      ALKALI
23   INTENTECH
24    INDORAMA

In [31]:
csv = pd.read_csv(r"C:\Users\ankul\Downloads\ank.csv")
csv

,SYMBOL,SECURITY,TODAY - VILUME,AVG - VOLUME,CHANGE,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11
0,ELECTHERM,Electrotherm,473907,9457,50.110003,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NBIFIN,N. B. I. Industrial Finance Company,5754,154,37.202586,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,HINDCON,Hindcon Private Limited,304759,9248,32.953450,NaN,NaN,NaN,NaN,NaN,NaN,
3,GKWLIMITED,GKW Limited,21375,711,30.049203,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,21STCENMGM,21st Century Management Service,110375,3879,28.450831,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,ALPHAGEO,Alphageo (India) Limited,232755,8356,27.852613,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,UNIENTER,Uniphos Enterprised Limited,162601,7553,21.528002,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,JAGSNPHARM,Jagsonpal Pharmaceutical Limited,1301892,73134,17.801420,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,SKMEGGPROD,SKM Egg Products Exportsn(India) Limited,1541130,87775,17.557733,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,SWELELCTES,Swelect Energy System Limited,207954,12276,16.938733,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,NAHARPOLY,Nahar Poly Film Limited,600043,38574,15.555297,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,PODDARHOUS,Poddar Housing and Development,46040,3012,15.283833,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,LINC,Linc Limited,60551,4076,14.853673,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,SHIVAMILLS,Shiva Mills Limited,142943,10391,13.755541,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,PDMJEPAPER,Pudumjee Paper Products Limited,1316284,102646,12.892143,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,DSSL,Dynacons System & Solution,263641,23439,11.247963,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,ANDREWYU,Andrew Yule & Company & Limited,2408026,230048,10.641332,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,LAXMICOT,Laxmi Costpin Limited,198503,19007,10.443312,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,REPL,Rudrabhishek Enterprises Limited,660281,65700,10.049911,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,PILITA,PIL ITALICA LIFESTYLE LIMITED,6864080,685602,10.017751,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,BHAGYAPROP,Bhagyanagar Properties Limited,305594,30596,9.987766,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,MUNJALAU,Munjal Auto Industries Limited,705322,82307,8.569312,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,ALKALI,Alkalis Metals Limited,157496,19069,8.563313,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,INTENTECH,Intense Technologies Limited,1252606,164644,7.607959,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,INDORAMA,Indo Rama Synthetic (India) Limited,679204,89288,7.606862,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [33]:
print(csv['CHANGE'])

0     50.110003
1     37.202586
2     32.953450
3     30.049203
4     28.450831
5     27.852613
6     21.528002
7     17.801420
8     17.557733
9     16.938733
10    15.555297
11    15.283833
12    14.853673
13    13.755541
14    12.892143
15    11.247963
16    10.641332
17    10.443312
18    10.049911
19    10.017751
20     9.987766
21     8.569312
22     8.563313
23     7.607959
24     7.606862
Name: CHANGE, dtype: float64

In [34]:
csv['CHANGE'] = csv['CHANGE'] + 1

In [35]:
csv

,SYMBOL,SECURITY,TODAY - VILUME,AVG - VOLUME,CHANGE,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11
0,ELECTHERM,Electrotherm,473907,9457,51.110003,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NBIFIN,N. B. I. Industrial Finance Company,5754,154,38.202586,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,HINDCON,Hindcon Private Limited,304759,9248,33.953450,NaN,NaN,NaN,NaN,NaN,NaN,
3,GKWLIMITED,GKW Limited,21375,711,31.049203,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,21STCENMGM,21st Century Management Service,110375,3879,29.450831,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,ALPHAGEO,Alphageo (India) Limited,232755,8356,28.852613,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,UNIENTER,Uniphos Enterprised Limited,162601,7553,22.528002,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,JAGSNPHARM,Jagsonpal Pharmaceutical Limited,1301892,73134,18.801420,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,SKMEGGPROD,SKM Egg Products Exportsn(India) Limited,1541130,87775,18.557733,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,SWELELCTES,Swelect Energy System Limited,207954,12276,17.938733,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,NAHARPOLY,Nahar Poly Film Limited,600043,38574,16.555297,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,PODDARHOUS,Poddar Housing and Development,46040,3012,16.283833,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,LINC,Linc Limited,60551,4076,15.853673,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,SHIVAMILLS,Shiva Mills Limited,142943,10391,14.755541,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,PDMJEPAPER,Pudumjee Paper Products Limited,1316284,102646,13.892143,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,DSSL,Dynacons System & Solution,263641,23439,12.247963,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,ANDREWYU,Andrew Yule & Company & Limited,2408026,230048,11.641332,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,LAXMICOT,Laxmi Costpin Limited,198503,19007,11.443312,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,REPL,Rudrabhishek Enterprises Limited,660281,65700,11.049911,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,PILITA,PIL ITALICA LIFESTYLE LIMITED,6864080,685602,11.017751,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,BHAGYAPROP,Bhagyanagar Properties Limited,305594,30596,10.987766,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,MUNJALAU,Munjal Auto Industries Limited,705322,82307,9.569312,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,ALKALI,Alkalis Metals Limited,157496,19069,9.563313,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,INTENTECH,Intense Technologies Limited,1252606,164644,8.607959,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,INDORAMA,Indo Rama Synthetic (India) Limited,679204,89288,8.606862,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [37]:
csv.head()

,SYMBOL,SECURITY,TODAY - VILUME,AVG - VOLUME,CHANGE,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11
0,ELECTHERM,Electrotherm,473907,9457,51.110003,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NBIFIN,N. B. I. Industrial Finance Company,5754,154,38.202586,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,HINDCON,Hindcon Private Limited,304759,9248,33.953450,NaN,NaN,NaN,NaN,NaN,NaN,
3,GKWLIMITED,GKW Limited,21375,711,31.049203,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,21STCENMGM,21st Century Management Service,110375,3879,29.450831,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [41]:
print(csv[['SYMBOL', 'SECURITY', 'CHANGE']])

        SYMBOL                                  SECURITY     CHANGE
0    ELECTHERM                              Electrotherm  51.110003
1       NBIFIN       N. B. I. Industrial Finance Company  38.202586
2      HINDCON                   Hindcon Private Limited  33.953450
3   GKWLIMITED                               GKW Limited  31.049203
4   21STCENMGM           21st Century Management Service  29.450831
5     ALPHAGEO                 Alphageo (India) Limited   28.852613
6     UNIENTER               Uniphos Enterprised Limited  22.528002
7   JAGSNPHARM          Jagsonpal Pharmaceutical Limited  18.801420
8   SKMEGGPROD  SKM Egg Products Exportsn(India) Limited  18.557733
9   SWELELCTES             Swelect Energy System Limited  17.938733
10   NAHARPOLY                   Nahar Poly Film Limited  16.555297
11  PODDARHOUS            Poddar Housing and Development  16.283833
12        LINC                              Linc Limited  15.853673
13  SHIVAMILLS                       Shiva Mills Limited  14.755541
14  PDMJEPAPER           Pudumjee Paper Products Limited  13.892143
15        DSSL                Dynacons System & Solution  12.247963
16    ANDREWYU           Andrew Yule & Company & Limited  11.641332
17    LAXMICOT                     Laxmi Costpin Limited  11.443312
18        REPL          Rudrabhishek Enterprises Limited  11.049911
19      PILITA             PIL ITALICA LIFESTYLE LIMITED  11.017751
20  BHAGYAPROP            Bhagyanagar Properties Limited  10.987766
21    MUNJALAU            Munjal Auto Industries Limited   9.569312
22      ALKALI                    Alkalis Metals Limited   9.563313
23   INTENTECH              Intense Technologies Limited   8.607959
24    INDORAMA       Indo Rama Synthetic (India) Limited   8.606862

In [42]:
csv = pd.read_csv(r"C:\Users\ankul\Downloads\ank.csv", usecols=[1,2])
csv

                                    SECURITY  TODAY - VILUME
0                               Electrotherm          473907
1        N. B. I. Industrial Finance Company            5754
2                    Hindcon Private Limited          304759
3                                GKW Limited           21375
4            21st Century Management Service          110375
5                  Alphageo (India) Limited           232755
6                Uniphos Enterprised Limited          162601
7           Jagsonpal Pharmaceutical Limited         1301892
8   SKM Egg Products Exportsn(India) Limited         1541130
9              Swelect Energy System Limited          207954
10                   Nahar Poly Film Limited          600043
11            Poddar Housing and Development           46040
12                              Linc Limited           60551
13                       Shiva Mills Limited          142943
14           Pudumjee Paper Products Limited         1316284
15                Dynacons System & Solution          263641
16           Andrew Yule & Company & Limited         2408026
17                     Laxmi Costpin Limited          198503
18          Rudrabhishek Enterprises Limited          660281
19             PIL ITALICA LIFESTYLE LIMITED         6864080
20            Bhagyanagar Properties Limited          305594
21            Munjal Auto Industries Limited          705322
22                    Alkalis Metals Limited          157496
23              Intense Technologies Limited         1252606
24       Indo Rama Synthetic (India) Limited          679204

In [ ]:
## These method is used for calling the columns
csv = pd.read_csv(r"C:\Users\ankul\Downloads\ank.csv")
columns = csv.columns[[1, 3]]
print(csv[columns])

                                    SECURITY  AVG - VOLUME
0                               Electrotherm          9457
1        N. B. I. Industrial Finance Company           154
2                    Hindcon Private Limited          9248
3                                GKW Limited           711
4            21st Century Management Service          3879
5                  Alphageo (India) Limited           8356
6                Uniphos Enterprised Limited          7553
7           Jagsonpal Pharmaceutical Limited         73134
8   SKM Egg Products Exportsn(India) Limited         87775
9              Swelect Energy System Limited         12276
10                   Nahar Poly Film Limited         38574
11            Poddar Housing and Development          3012
12                              Linc Limited          4076
13                       Shiva Mills Limited         10391
14           Pudumjee Paper Products Limited        102646
15                Dynacons System & Solution         23439
16           Andrew Yule & Company & Limited        230048
17                     Laxmi Costpin Limited         19007
18          Rudrabhishek Enterprises Limited         65700
19             PIL ITALICA LIFESTYLE LIMITED        685602
20            Bhagyanagar Properties Limited         30596
21            Munjal Auto Industries Limited         82307
22                    Alkalis Metals Limited         19069
23              Intense Technologies Limited        164644
24       Indo Rama Synthetic (India) Limited         89288

In [ ]:
# skip the row number 0 and row 3 we use skiprows method.
csv = pd.read_csv(r"C:\Users\ankul\Downloads\ank.csv", skiprows=[0,3])
csv

,ELECTHERM,Electrotherm,473907,9457,50.11000282,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11
0,NBIFIN,N. B. I. Industrial Finance Company,5754,154,37.202586,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,GKWLIMITED,GKW Limited,21375,711,30.049203,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,21STCENMGM,21st Century Management Service,110375,3879,28.450831,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,ALPHAGEO,Alphageo (India) Limited,232755,8356,27.852613,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,UNIENTER,Uniphos Enterprised Limited,162601,7553,21.528002,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,JAGSNPHARM,Jagsonpal Pharmaceutical Limited,1301892,73134,17.801420,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,SKMEGGPROD,SKM Egg Products Exportsn(India) Limited,1541130,87775,17.557733,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,SWELELCTES,Swelect Energy System Limited,207954,12276,16.938733,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,NAHARPOLY,Nahar Poly Film Limited,600043,38574,15.555297,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,PODDARHOUS,Poddar Housing and Development,46040,3012,15.283833,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,LINC,Linc Limited,60551,4076,14.853673,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,SHIVAMILLS,Shiva Mills Limited,142943,10391,13.755541,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,PDMJEPAPER,Pudumjee Paper Products Limited,1316284,102646,12.892143,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,DSSL,Dynacons System & Solution,263641,23439,11.247963,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,ANDREWYU,Andrew Yule & Company & Limited,2408026,230048,10.641332,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,LAXMICOT,Laxmi Costpin Limited,198503,19007,10.443312,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,REPL,Rudrabhishek Enterprises Limited,660281,65700,10.049911,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,PILITA,PIL ITALICA LIFESTYLE LIMITED,6864080,685602,10.017751,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,BHAGYAPROP,Bhagyanagar Properties Limited,305594,30596,9.987766,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,MUNJALAU,Munjal Auto Industries Limited,705322,82307,8.569312,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,ALKALI,Alkalis Metals Limited,157496,19069,8.563313,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,INTENTECH,Intense Technologies Limited,1252606,164644,7.607959,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,INDORAMA,Indo Rama Synthetic (India) Limited,679204,89288,7.606862,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
## index_col method make SYMBOL to index
csv_2 = pd.read_csv(r"C:\Users\ankul\Downloads\ank.csv", index_col=['SYMBOL'])
csv_2

,SECURITY,TODAY - VILUME,AVG - VOLUME,CHANGE,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11
SYMBOL,,,,,,,,,,,
ELECTHERM,Electrotherm,473907,9457,50.110003,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NBIFIN,N. B. I. Industrial Finance Company,5754,154,37.202586,NaN,NaN,NaN,NaN,NaN,NaN,NaN
HINDCON,Hindcon Private Limited,304759,9248,32.953450,NaN,NaN,NaN,NaN,NaN,NaN,
GKWLIMITED,GKW Limited,21375,711,30.049203,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21STCENMGM,21st Century Management Service,110375,3879,28.450831,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ALPHAGEO,Alphageo (India) Limited,232755,8356,27.852613,NaN,NaN,NaN,NaN,NaN,NaN,NaN
UNIENTER,Uniphos Enterprised Limited,162601,7553,21.528002,NaN,NaN,NaN,NaN,NaN,NaN,NaN
JAGSNPHARM,Jagsonpal Pharmaceutical Limited,1301892,73134,17.801420,NaN,NaN,NaN,NaN,NaN,NaN,NaN
SKMEGGPROD,SKM Egg Products Exportsn(India) Limited,1541130,87775,17.557733,NaN,NaN,NaN,NaN,NaN,NaN,NaN
SWELELCTES,Swelect Energy System Limited,207954,12276,16.938733,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NAHARPOLY,Nahar Poly Film Limited,600043,38574,15.555297,NaN,NaN,NaN,NaN,NaN,NaN,NaN
PODDARHOUS,Poddar Housing and Development,46040,3012,15.283833,NaN,NaN,NaN,NaN,NaN,NaN,NaN
LINC,Linc Limited,60551,4076,14.853673,NaN,NaN,NaN,NaN,NaN,NaN,NaN
SHIVAMILLS,Shiva Mills Limited,142943,10391,13.755541,NaN,NaN,NaN,NaN,NaN,NaN,NaN
PDMJEPAPER,Pudumjee Paper Products Limited,1316284,102646,12.892143,NaN,NaN,NaN,NaN,NaN,NaN,NaN
DSSL,Dynacons System & Solution,263641,23439,11.247963,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ANDREWYU,Andrew Yule & Company & Limited,2408026,230048,10.641332,NaN,NaN,NaN,NaN,NaN,NaN,NaN
LAXMICOT,Laxmi Costpin Limited,198503,19007,10.443312,NaN,NaN,NaN,NaN,NaN,NaN,NaN
REPL,Rudrabhishek Enterprises Limited,660281,65700,10.049911,NaN,NaN,NaN,NaN,NaN,NaN,NaN
PILITA,PIL ITALICA LIFESTYLE LIMITED,6864080,685602,10.017751,NaN,NaN,NaN,NaN,NaN,NaN,NaN
BHAGYAPROP,Bhagyanagar Properties Limited,305594,30596,9.987766,NaN,NaN,NaN,NaN,NaN,NaN,NaN
MUNJALAU,Munjal Auto Industries Limited,705322,82307,8.569312,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ALKALI,Alkalis Metals Limited,157496,19069,8.563313,NaN,NaN,NaN,NaN,NaN,NaN,NaN
INTENTECH,Intense Technologies Limited,1252606,164644,7.607959,NaN,NaN,NaN,NaN,NaN,NaN,NaN
INDORAMA,Indo Rama Synthetic (India) Limited,679204,89288,7.606862,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [54]:
## Header parameter make header any row as you want
csv_2 = pd.read_csv(r"C:\Users\ankul\Downloads\ank.csv", header=2)
csv_2

,NBIFIN,N. B. I. Industrial Finance Company,5754,154,37.20258621,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11
0,HINDCON,Hindcon Private Limited,304759,9248,32.953450,NaN,NaN,NaN,NaN,NaN,NaN,
1,GKWLIMITED,GKW Limited,21375,711,30.049203,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,21STCENMGM,21st Century Management Service,110375,3879,28.450831,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,ALPHAGEO,Alphageo (India) Limited,232755,8356,27.852613,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,UNIENTER,Uniphos Enterprised Limited,162601,7553,21.528002,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,JAGSNPHARM,Jagsonpal Pharmaceutical Limited,1301892,73134,17.801420,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,SKMEGGPROD,SKM Egg Products Exportsn(India) Limited,1541130,87775,17.557733,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,SWELELCTES,Swelect Energy System Limited,207954,12276,16.938733,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,NAHARPOLY,Nahar Poly Film Limited,600043,38574,15.555297,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,PODDARHOUS,Poddar Housing and Development,46040,3012,15.283833,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,LINC,Linc Limited,60551,4076,14.853673,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,SHIVAMILLS,Shiva Mills Limited,142943,10391,13.755541,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,PDMJEPAPER,Pudumjee Paper Products Limited,1316284,102646,12.892143,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,DSSL,Dynacons System & Solution,263641,23439,11.247963,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,ANDREWYU,Andrew Yule & Company & Limited,2408026,230048,10.641332,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,LAXMICOT,Laxmi Costpin Limited,198503,19007,10.443312,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,REPL,Rudrabhishek Enterprises Limited,660281,65700,10.049911,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,PILITA,PIL ITALICA LIFESTYLE LIMITED,6864080,685602,10.017751,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,BHAGYAPROP,Bhagyanagar Properties Limited,305594,30596,9.987766,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,MUNJALAU,Munjal Auto Industries Limited,705322,82307,8.569312,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,ALKALI,Alkalis Metals Limited,157496,19069,8.563313,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,INTENTECH,Intense Technologies Limited,1252606,164644,7.607959,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,INDORAMA,Indo Rama Synthetic (India) Limited,679204,89288,7.606862,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [58]:
## name method is used for change the heading
csv_2 = pd.read_csv(r"C:\Users\ankul\Downloads\ank.csv",names=['col1','col2','ank3','sri4','sad5','sur6','None','chan','vol12'])
csv_2

,,,col1,col2,ank3,sri4,sad5,sur6,None,chan,vol12
SYMBOL,SECURITY,TODAY - VILUME,AVG - VOLUME,CHANGE,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ELECTHERM,Electrotherm,473907,9457,50.11000282,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NBIFIN,N. B. I. Industrial Finance Company,5754,154,37.20258621,NaN,NaN,NaN,NaN,NaN,NaN,NaN
HINDCON,Hindcon Private Limited,304759,9248,32.95345023,NaN,NaN,NaN,NaN,NaN,NaN,
GKWLIMITED,GKW Limited,21375,711,30.04920337,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21STCENMGM,21st Century Management Service,110375,3879,28.45083129,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ALPHAGEO,Alphageo (India) Limited,232755,8356,27.85261268,NaN,NaN,NaN,NaN,NaN,NaN,NaN
UNIENTER,Uniphos Enterprised Limited,162601,7553,21.52800212,NaN,NaN,NaN,NaN,NaN,NaN,NaN
JAGSNPHARM,Jagsonpal Pharmaceutical Limited,1301892,73134,17.80141977,NaN,NaN,NaN,NaN,NaN,NaN,NaN
SKMEGGPROD,SKM Egg Products Exportsn(India) Limited,1541130,87775,17.55773284,NaN,NaN,NaN,NaN,NaN,NaN,NaN
SWELELCTES,Swelect Energy System Limited,207954,12276,16.93873284,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NAHARPOLY,Nahar Poly Film Limited,600043,38574,15.55529728,NaN,NaN,NaN,NaN,NaN,NaN,NaN
PODDARHOUS,Poddar Housing and Development,46040,3012,15.28383313,NaN,NaN,NaN,NaN,NaN,NaN,NaN
LINC,Linc Limited,60551,4076,14.85367349,NaN,NaN,NaN,NaN,NaN,NaN,NaN
SHIVAMILLS,Shiva Mills Limited,142943,10391,13.7555413,NaN,NaN,NaN,NaN,NaN,NaN,NaN
PDMJEPAPER,Pudumjee Paper Products Limited,1316284,102646,12.89214253,NaN,NaN,NaN,NaN,NaN,NaN,NaN
DSSL,Dynacons System & Solution,263641,23439,11.24796282,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ANDREWYU,Andrew Yule & Company & Limited,2408026,230048,10.64133195,NaN,NaN,NaN,NaN,NaN,NaN,NaN
LAXMICOT,Laxmi Costpin Limited,198503,19007,10.44331235,NaN,NaN,NaN,NaN,NaN,NaN,NaN
REPL,Rudrabhishek Enterprises Limited,660281,65700,10.04991136,NaN,NaN,NaN,NaN,NaN,NaN,NaN
PILITA,PIL ITALICA LIFESTYLE LIMITED,6864080,685602,10.01775122,NaN,NaN,NaN,NaN,NaN,NaN,NaN
BHAGYAPROP,Bhagyanagar Properties Limited,305594,30596,9.987765618,NaN,NaN,NaN,NaN,NaN,NaN,NaN
MUNJALAU,Munjal Auto Industries Limited,705322,82307,8.569311803,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ALKALI,Alkalis Metals Limited,157496,19069,8.563313454,NaN,NaN,NaN,NaN,NaN,NaN,NaN
INTENTECH,Intense Technologies Limited,1252606,164644,7.607958578,NaN,NaN,NaN,NaN,NaN,NaN,NaN
INDORAMA,Indo Rama Synthetic (India) Limited,679204,89288,7.606861665,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [59]:
## name method is used for change the heading
csv_2 = pd.read_csv(r"C:\Users\ankul\Downloads\ank.csv",header=None)
csv_2

,0,1,2,3,4,5,6,7,8,9,10,11
0,SYMBOL,SECURITY,TODAY - VILUME,AVG - VOLUME,CHANGE,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,ELECTHERM,Electrotherm,473907,9457,50.11000282,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NBIFIN,N. B. I. Industrial Finance Company,5754,154,37.20258621,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,HINDCON,Hindcon Private Limited,304759,9248,32.95345023,NaN,NaN,NaN,NaN,NaN,NaN,
4,GKWLIMITED,GKW Limited,21375,711,30.04920337,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,21STCENMGM,21st Century Management Service,110375,3879,28.45083129,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,ALPHAGEO,Alphageo (India) Limited,232755,8356,27.85261268,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,UNIENTER,Uniphos Enterprised Limited,162601,7553,21.52800212,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,JAGSNPHARM,Jagsonpal Pharmaceutical Limited,1301892,73134,17.80141977,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,SKMEGGPROD,SKM Egg Products Exportsn(India) Limited,1541130,87775,17.55773284,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,SWELELCTES,Swelect Energy System Limited,207954,12276,16.93873284,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,NAHARPOLY,Nahar Poly Film Limited,600043,38574,15.55529728,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,PODDARHOUS,Poddar Housing and Development,46040,3012,15.28383313,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,LINC,Linc Limited,60551,4076,14.85367349,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,SHIVAMILLS,Shiva Mills Limited,142943,10391,13.7555413,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,PDMJEPAPER,Pudumjee Paper Products Limited,1316284,102646,12.89214253,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,DSSL,Dynacons System & Solution,263641,23439,11.24796282,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,ANDREWYU,Andrew Yule & Company & Limited,2408026,230048,10.64133195,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,LAXMICOT,Laxmi Costpin Limited,198503,19007,10.44331235,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,REPL,Rudrabhishek Enterprises Limited,660281,65700,10.04991136,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,PILITA,PIL ITALICA LIFESTYLE LIMITED,6864080,685602,10.01775122,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,BHAGYAPROP,Bhagyanagar Properties Limited,305594,30596,9.987765618,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,MUNJALAU,Munjal Auto Industries Limited,705322,82307,8.569311803,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,ALKALI,Alkalis Metals Limited,157496,19069,8.563313454,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,INTENTECH,Intense Technologies Limited,1252606,164644,7.607958578,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,INDORAMA,Indo Rama Synthetic (India) Limited,679204,89288,7.606861665,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
## giving prefix parameter
import pandas as pd

df = pd.read_csv(r"C:\Users\ankul\Downloads\ank.csv", header=None)

# Rename columns with a prefix
df.columns = [f'col{i}' for i in range(df.shape[1])]

print(df)

          col0                                      col1            col2  \
0       SYMBOL                                  SECURITY  TODAY - VILUME
1    ELECTHERM                              Electrotherm          473907
2       NBIFIN       N. B. I. Industrial Finance Company            5754
3      HINDCON                   Hindcon Private Limited          304759
4   GKWLIMITED                               GKW Limited           21375
5   21STCENMGM           21st Century Management Service          110375
6     ALPHAGEO                 Alphageo (India) Limited           232755
7     UNIENTER               Uniphos Enterprised Limited          162601
8   JAGSNPHARM          Jagsonpal Pharmaceutical Limited         1301892
9   SKMEGGPROD  SKM Egg Products Exportsn(India) Limited         1541130
10  SWELELCTES             Swelect Energy System Limited          207954
11   NAHARPOLY                   Nahar Poly Film Limited          600043
12  PODDARHOUS            Poddar Housing and Development           46040
13        LINC                              Linc Limited           60551
14  SHIVAMILLS                       Shiva Mills Limited          142943
15  PDMJEPAPER           Pudumjee Paper Products Limited         1316284
16        DSSL                Dynacons System & Solution          263641
17    ANDREWYU           Andrew Yule & Company & Limited         2408026
18    LAXMICOT                     Laxmi Costpin Limited          198503
19        REPL          Rudrabhishek Enterprises Limited          660281
20      PILITA             PIL ITALICA LIFESTYLE LIMITED         6864080
21  BHAGYAPROP            Bhagyanagar Properties Limited          305594
22    MUNJALAU            Munjal Auto Industries Limited          705322
23      ALKALI                    Alkalis Metals Limited          157496
24   INTENTECH              Intense Technologies Limited         1252606
25    INDORAMA       Indo Rama Synthetic (India) Limited          679204

            col3         col4  col5  col6  col7  col8  col9  col10 col11
0   AVG - VOLUME       CHANGE   NaN   NaN   NaN   NaN   NaN    NaN   NaN
1           9457  50.11000282   NaN   NaN   NaN   NaN   NaN    NaN   NaN
2            154  37.20258621   NaN   NaN   NaN   NaN   NaN    NaN   NaN
3           9248  32.95345023   NaN   NaN   NaN   NaN   NaN    NaN
4            711  30.04920337   NaN   NaN   NaN   NaN   NaN    NaN   NaN
5           3879  28.45083129   NaN   NaN   NaN   NaN   NaN    NaN   NaN
6           8356  27.85261268   NaN   NaN   NaN   NaN   NaN    NaN   NaN
7           7553  21.52800212   NaN   NaN   NaN   NaN   NaN    NaN   NaN
8          73134  17.80141977   NaN   NaN   NaN   NaN   NaN    NaN   NaN
9          87775  17.55773284   NaN   NaN   NaN   NaN   NaN    NaN   NaN
10         12276  16.93873284   NaN   NaN   NaN   NaN   NaN    NaN   NaN
11         38574  15.55529728   NaN   NaN   NaN   NaN   NaN    NaN   NaN
12          3012  15.28383313   NaN   NaN   NaN   NaN   NaN    NaN   NaN
13          4076  14.85367349   NaN   NaN   NaN   NaN   NaN    NaN   NaN
14         10391   13.7555413   NaN   NaN   NaN   NaN   NaN    NaN   NaN
15        102646  12.89214253   NaN   NaN   NaN   NaN   NaN    NaN   NaN
16         23439  11.24796282   NaN   NaN   NaN   NaN   NaN    NaN   NaN
17        230048  10.64133195   NaN   NaN   NaN   NaN   NaN    NaN   NaN
18         19007  10.44331235   NaN   NaN   NaN   NaN   NaN    NaN   NaN
19         65700  10.04991136   NaN   NaN   NaN   NaN   NaN    NaN   NaN
20        685602  10.01775122   NaN   NaN   NaN   NaN   NaN    NaN   NaN
21         30596  9.987765618   NaN   NaN   NaN   NaN   NaN    NaN   NaN
22         82307  8.569311803   NaN   NaN   NaN   NaN   NaN    NaN   NaN
23         19069  8.563313454   NaN   NaN   NaN   NaN   NaN    NaN   NaN
24        164644  7.607958578   NaN   NaN   NaN   NaN   NaN    NaN   NaN
25         89288  7.606861665   NaN   NaN   NaN   NaN   NaN    NaN   NaN

In [67]:
csv_2 = pd.read_csv(r"C:\Users\ankul\Downloads\ank.csv", dtype={"Today-Valume":"float"})
csv_2

,SYMBOL,SECURITY,TODAY - VILUME,AVG - VOLUME,CHANGE,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11
0,ELECTHERM,Electrotherm,473907,9457,50.110003,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NBIFIN,N. B. I. Industrial Finance Company,5754,154,37.202586,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,HINDCON,Hindcon Private Limited,304759,9248,32.953450,NaN,NaN,NaN,NaN,NaN,NaN,
3,GKWLIMITED,GKW Limited,21375,711,30.049203,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,21STCENMGM,21st Century Management Service,110375,3879,28.450831,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,ALPHAGEO,Alphageo (India) Limited,232755,8356,27.852613,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,UNIENTER,Uniphos Enterprised Limited,162601,7553,21.528002,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,JAGSNPHARM,Jagsonpal Pharmaceutical Limited,1301892,73134,17.801420,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,SKMEGGPROD,SKM Egg Products Exportsn(India) Limited,1541130,87775,17.557733,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,SWELELCTES,Swelect Energy System Limited,207954,12276,16.938733,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,NAHARPOLY,Nahar Poly Film Limited,600043,38574,15.555297,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,PODDARHOUS,Poddar Housing and Development,46040,3012,15.283833,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,LINC,Linc Limited,60551,4076,14.853673,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,SHIVAMILLS,Shiva Mills Limited,142943,10391,13.755541,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,PDMJEPAPER,Pudumjee Paper Products Limited,1316284,102646,12.892143,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,DSSL,Dynacons System & Solution,263641,23439,11.247963,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,ANDREWYU,Andrew Yule & Company & Limited,2408026,230048,10.641332,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,LAXMICOT,Laxmi Costpin Limited,198503,19007,10.443312,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,REPL,Rudrabhishek Enterprises Limited,660281,65700,10.049911,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,PILITA,PIL ITALICA LIFESTYLE LIMITED,6864080,685602,10.017751,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,BHAGYAPROP,Bhagyanagar Properties Limited,305594,30596,9.987766,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,MUNJALAU,Munjal Auto Industries Limited,705322,82307,8.569312,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,ALKALI,Alkalis Metals Limited,157496,19069,8.563313,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,INTENTECH,Intense Technologies Limited,1252606,164644,7.607959,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,INDORAMA,Indo Rama Synthetic (India) Limited,679204,89288,7.606862,NaN,NaN,NaN,NaN,NaN,NaN,NaN